# Generated by Django 5.2.6 on 2025-09-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('desktop_users', models.IntegerField()),
                ('mobile_users', models.IntegerField()),
            ],
            options={
                'db_table': 'user_analytics',
                'managed': False,
            },
        ),
    ]
