version: "3.8"

services:
  web:
    build: ./sbm_backend
    command: sh -c "uv run manage.py migrate && uv run manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./sbm_backend:/usr/src/sbm_backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "sbmdb", "-U", "postgresuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=sbmdb
    pull_policy: always

volumes:
  postgres_data:
